### ISSUE TITLE
IllegalArgumentException: rate must be positive

### ISSUE THREAD

**Issue by lepirlouit** [audienceproject/spark-dynamodb#12]
Issue on table in billing mode PAY_PER_REQUEST (on demand)

Rate cannot be computed because there is no Provisioned Throughput, no Read/Write capacity units.

https://github.com/audienceproject/spark-dynamodb/blob/ccbcf0f5eca46516cc48100956b51e7e13060c11/src/main/scala/com/audienceproject/spark/dynamodb/connector/TableConnector.scala#L54-L58

Requests will not be throttled in that case.

**Comment by jacobfi** [comment]
Hi lepirlouit
Thank you for bringing this to our attention.
It has been taken care of with this commit https://github.com/audienceproject/spark-dynamodb/commit/e7d3d43e20e65b176a11147aa56b3765bb6488a6 and will be out in version 0.3.4
The connector will aim for a capacity of 100 when using on-demand. You can bump this up or down with the `targetCapacity` parameter, e.g. with a target capacity of 10 you will get 1000 on-demand throughput.
Regards,
Jacob
