### ISSUE TITLE
Write nested Object in DynamoDB

### ISSUE THREAD

**Issue by lucienfregosi** [audienceproject/spark-dynamodb#20]
When I try to write a complex dataset (based on a  case class for the data model) in dynamoDB with some nested sub object like (just an example) : 
{
    "HashKey": 1,
    "MyObject": [
     {
        "ProductId":100,
        "Quantity": 50
     }
     ]
}
I received this error message from dynamo : "AmazonDynamoDBException: One or more parameter values were invalid: An AttributeValue may not contain an empty string" which is dumb because there is obviously no empty string.

Is it a bug ? Or does the connector only manage flat object ?

**Comment by jacobfi** [comment]
Hi
What does your case class look like?
Could you send the whole stacktrace?

**Comment by lucienfregosi** [comment]
I have two case class 
Main one : `case class Model(companyId : Long, requestTimestamp: Long, address : Address)`
Second one : `case class Address(postalCode: String, city: String)`

My Spark dataset is based on these 2 case class

And you can have the entire stack trace here : [](https://pastebin.com/5z3eM1tw)

Thanks for your help :)

**Comment by jacobfi** [comment]
HI lucien
I have reproduced your error, and I think the problem is that you have empty strings in one or more of the rows in your dataset (e.g. postalCode="")
The problem is that DynamoDB does not accept empty strings as values. I suggest that you fix the problem by filtering out the violating rows or setting empty string values to null.

**Comment by lucienfregosi** [comment]
Hi Jacob
Thanks for your answer your were right !
I had to write a lot of spark code to replace all the empty value with null in a really complex and nested structure...
But it works nom :)
Many thanks for your help and your work on that project

**Comment by jacobfi** [comment]
Thank you!
