### ISSUE TITLE
sbt package fails with unresolved dependency: com.jsuereth#sbt-pgp;1.1.1

### ISSUE THREAD

**Issue by javadba** [audienceproject/spark-dynamodb#21]
Running `sbt package` results in:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.jsuereth#sbt-pgp;1.1.1: not found
[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found
[warn] 	:: com.dwijnand#sbt-compat;1.2.6: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

How can this be compiled/built?

**Comment by jacobfi** [comment]
Hi javadba
This library is not meant to be packaged alone, but included in other projects.
Assuming you have such a project, do you have a Maven resolver in your `build.sbt`? Something like this:
`resolvers += "WSO2" at "http://dist.wso2.org/maven2/"`

**Comment by javadba** [comment]
Thx. The projects I work on use maven and not sbt. What would be the process to include this library?

**Comment by jacobfi** [comment]
Hi again
Does putting the dependency in your pom.xml not work?
```
<dependency>
  <groupId>com.audienceproject</groupId>
  <artifactId>spark-dynamodb_2.11</artifactId>
  <version>0.4.0</version>
</dependency>
```

**Comment by javadba** [comment]
I had tried maven first - before sbt -  and believe it resulted in the same
error. I reported the sbt package version of the error since it is the more
native way to build this project.

Am Fr., 22. März 2019 um 02:02 Uhr schrieb Jacob Fischer <
notifications@github.com>:

**Comment by jacobfi** [comment]
Hi again,
I can run `mvn compile` on a Scala project with the dependency in the pom.xml as written above just fine.
I am unsure what your problem is, could you provide more detail?

**Comment by cosmincatalin** [comment]
Hi @javadba, I'll close the issue because of lack of activity. If you still have issue, please reopen.
