### ISSUE TITLE
V0.4.0 tanks write performance

### ISSUE THREAD

**Issue by colemanja91** [audienceproject/spark-dynamodb#22]
**Issue:** Upgrading to v0.4.0 seems to kill any previous parallelism benefits - only really writing ~25 records at a time. 

![image](https://user-images.githubusercontent.com/2940547/54935585-f91f2500-4ef6-11e9-940b-9c7e12675fd0.png)

The above screenshot (from DynamoDB console) illustrates. There's a slight bump in the consumed write capacity right before 16:00 - this is using v0.4.0. The spike a few minutes after that is the exact same job, using v0.3.6. 

**Expected behavior:** Parallelism on writes should be same as V0.3.6.

**Comment by jacobfi** [comment]
Hi colemanja
Can you find out what the `spark.sparkContext.defaultParallelism` is set to in your Spark program?
Also, how large (in bytes) is an average row in your dataset? Are you doing writes or updates (flag `update=true`)?

I can't seem to reproduce your problem right out of the box:
![image](https://user-images.githubusercontent.com/5450413/55063264-ec760a80-5077-11e9-898a-11c5565d3b67.png)

**Comment by colemanja91** [comment]
Default parallelism: 72
Average item size: 1,127 bytes
We're strictly doing writes - not setting anything other than region, actually:

```
df
  .write
  .option("region", awsRegion)
  .dynamodb(tableName)
```

**Comment by colemanja91** [comment]
@jacobfi Awesome - thanks for digging into it!
