### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by aelesbao** [audienceproject/spark-dynamodb#23]
Hi all,

First of all, thanks for this project! It made my life really easy when exporting data from DynamoDB.

I just would like to know if you mind adding git tags to the repository every time you release a new version. This would be really helpful to navigate on the source and correlate possible issues with the version we have running in production.

**Comment by cosmincatalin** [comment]
Hi @aelesbao, we have just tagged the latest version and we'll make sure we do that looking forward.
