### ISSUE TITLE
targetCapacity when executors != readPartitions

### ISSUE THREAD

**Issue by protometa** [audienceproject/spark-dynamodb#24]
If readPartitions is set, the targetCapacity seems to be based solely on that and not actual number of executors. Is this correct? If so it's worth noting that targetCapacity may not be accurate if you set readPartitions and use a different number of executor cores.

**Comment by jacobfi** [comment]
Hi protometa

The `readPartitions` option is intended as an override in case you need to micromanage the number of tasks reading in parallel, or how distributed the dataset is on the cluster. (Example: maybe you have hundreds of executor-cores but a very small database table, and reading it from just a few cores would be quick.)

I realize we may have a bug in that the read limit per executor-core is calculated based on number of partitions, so if `readPartitions < defaultParallelism` then it will read with max capacity, but if `readPartitions > defaultParallelism` the read limit will be much lower than it should. The formula should probably be `totalSegments = min(readPartitions, defaultParallelism)` but the RDD should partition into `readPartitions.getOrElse(defaultParallelism)`.

I would fix it but right now I am regrettably busy with other things.

**Comment by jacobfi** [comment]
Hello
The newest release 1.0.0 has introduced some improvements to the throughput/parallelism calculation, which should solve this problem.
Closing this issue.
