### ISSUE TITLE
Can't change the region

### ISSUE THREAD

**Issue by anuras** [audienceproject/spark-dynamodb#27]
Hi!
I might be missing something but it seems to me that it's not possible(?) to use the library in regions other than us-east-1, at least in linux environments.
`aws.dynamodb.region` is not a valid identifier for an environment variable, at least in bash. Simple fix could be just changing that to `AWS_DYNAMODB_REGION`?
This the line I'm referring to:
https://github.com/audienceproject/spark-dynamodb/blob/ee645ecb3eaff844dc8f8127054f6f82dac58c1e/src/main/scala/com/audienceproject/spark/dynamodb/connector/DynamoConnector.scala#L38

**Comment by impxia** [comment]
In the REAME, it mentioned there is an option named `region`. So you can change region by something like
```
val dynamoDf = spark.read.option("region", "us-west-2").dynamodb("SomeTableName")
```
