### ISSUE TITLE
Performance issue writing in DynamoDB

### ISSUE THREAD

**Issue by lucienfregosi** [audienceproject/spark-dynamodb#30]
Hi I have some performance issue writing in an "on demand" scaling DynamoDB Table with audience connector.

With a cluster with 1 m5.xlarge master and 2 m5.xlarge core nodes I am stuck with 300 WCU on dynamo which is pretty slow.

I tried a lot of different Spark configuration but it doesn't change anything. The only way to improve my write capacity is to increase my instance type to m5.4xlarge for example..

I am running a simple ETL Spark job reading in S3, a bit of processing and writing data in DynamoDB.
I m using the 0.4.0 version for audience connector and emr-5.20.0 for EMR version.

Many thanks for your help

**Comment by johsbk** [comment]
you can always change the capacity configuration of the DynamoDB table
through the api before and after the writing.

**Comment by lucienfregosi** [comment]
Hi, thanks for your reply
As my dynamodb table is on-demand scaling I don't need to change the capacity configuration isn't ?

**Comment by jacobfi** [comment]
Hi lucienfregosi
Have you tried setting the `targetCapacity` parameter? When the table is on-demand the connector defaults to 100 capacity.
If you set `.option("targetCapacity", "10")` it will aim for 1000 instead.

**Comment by lucienfregosi** [comment]
Awesome 👍 It works with 10 (2000 WCU) but I have even better performance with 100.
The default value seems to be 1 the WCU are the same than no target capacity. Is it normal ?
Thank you for your help!
