### ISSUE TITLE
On demand capacity

### ISSUE THREAD

**Issue by liorwinner** [audienceproject/spark-dynamodb#32]
When reading/writing to dynamo tables with on-demand capacity mode, the connector uses the default value (100L) instead of unlimited value. In order to support the large scale we are using, we had to change the table configuration to a high provisioned capacity in order to acheive better performance than maximum 100 reads on average. On the long term we would like to return to on demand usage to support unlimited capacity.

**Comment by cosmincatalin** [comment]
Hi @liorwinner , the idea is that the connector would not use capacity beyond what is provisioned upfront. I assume what you mean by unlimited is in fact auto scaling. In that case we use a reasonable default (100). The thing is that if you want to go from zero to hero, hero might be really, really high. I think the best option for this use case is to specify a desired throughput. I will look into what is needed to make this happen.

**Comment by liorwinner** [comment]
hey @cosmincatalin thanks for the quick response!
Actually i was not talking about auto scaling, but the other option to choose "on-demand" capacity. which basically gives you pay per request pricing for read and write requests. Thats a quite new billing option for DynamoDB that doesn't require capacity planning in advance.

**Comment by cosmincatalin** [comment]
Right. I will say that for this case too, my response holds.
In any case, would allowing setting the write throughput manually be an acceptable solution for you, @liorwinner ?

**Comment by liorwinner** [comment]
yeah i believe that setting the read/write throughput manually will totally do the work :-)

**Comment by cosmincatalin** [comment]
Update has been merged to master and it will go with the next release, which should be as soon as we manage to get Github Actions working.

**Comment by liorwinner** [comment]
Thanks a lot! 
Do you have any time estimation for the next release?

**Comment by cosmincatalin** [comment]
Unfortunately we are caught in some higher priority projects at the moment and cannot give an ETA. As a workaround you can set the `targetCapacity` to a value that corresponds to the capacity you want. Eg: if you need throughput 4000, just set it to 40, which is 40 * 100. Less elegant, but works.

**Comment by Andrew-Tan** [comment]
@cosmincatalin Facing a similar issue when using provisioned throughput. 

Say I have a table with 10000 write capacity unit. With `targetCapacity` set to 1, the consumed capacity plateau at ~4000. Do you have a formula to maximize provision throughput also?

**Comment by cosmincatalin** [comment]
Sounds like something is off, but it is difficult to figure out it is juts with this information alone.
If the table is provisioned with an on-demand capacity of 10.000, the connector should write with 10.000, unless some of your executors have died, or you have changed the capacity after the program has started running (see #37 ).
In any case, you can always try bumping up the `targetCapacity` to some other higher number until you're satisfied with the throughput.

**Comment by Andrew-Tan** [comment]
I see. I'll poke around with the number.

**Comment by cosmincatalin** [comment]
Version `0.4.4` is going right now to Maven Central. Reopen this if issues occur.
