### ISSUE TITLE
Stop using guava

### ISSUE THREAD

**Issue by AceHack** [audienceproject/spark-dynamodb#35]
or update to a newer version, there are too many dependency issues

**Comment by cosmincatalin** [comment]
Hi @AceHack, updating to a newer version of Guava would create additional complications in relation to the version that Spark uses by default. We will look into the possibility of removing it all together.

**Comment by AceHack** [comment]
@cosmincatalin so if you actually look at the lastest spark release without hadoop it does not include Guava at all.
https://www-us.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-without-hadoop.tgz

You can see in the jars folder there is no guava jar.

Thanks and I would love to see just removing it altogether, it causes us so much headache.

**Comment by cosmincatalin** [comment]
As can be seen [here](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/2.4.4), Guava is still a dependency, even if the distribution for Hadoop does not include it.

Until we decide what to do with Guava looking forward, I think you can try to exclude the Guava dependency when you build your own jar or you can use shading (although I am not very familiar with this technique).

**Comment by AceHack** [comment]
It’s the distribution for spark server without Hadoop that does not include it to be clear.

**Comment by AceHack** [comment]
Please remove this, it's now blocking from fixing CVEs in our spark base image.  Thanks.

**Comment by cosmincatalin** [comment]
I've pulled out Guava. See commit 7e126169332c8b4da666b4bd55dbe36763fe6d4f. It will take a few more days until we release, so we have some time to test.

**Comment by AceHack** [comment]
@cosmincatalin You are the man!!! That is awesome.

**Comment by cosmincatalin** [comment]
This is taking longer than expected. We have some problem when publishing to scala 2.12.

**Comment by Larkhis** [comment]
Hi @cosmincatalin can you publish first to scala 2.11 until you resolve the problems with 2.12 ?
And thanks a lot.

**Comment by cosmincatalin** [comment]
I have just release `0.4.4`. Let me know if it is everything you wanted it 😄 and reopen as necessary.

**Comment by cosmincatalin** [comment]
Unfortunately,  there has been a mistake. The Guava path did not get merged. I will do another try this week and make a new release. Sorry for keeping all of you waiting for so long.
