### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/spark_project/guava/util/concurrent/RateLimiter

### ISSUE THREAD

**Issue by yeungp** [audienceproject/spark-dynamodb#4]
I'm using spark-dynamodb_2.11:0.2.2 from https://oss.sonatype.org
I got no RateLimiter class error when I write to a dynamo table as below,

newItemsDs.write.dynamodb("table-name")

I use the jar from https://mvnrepository.com/artifact/com.google.guava/guava/26.0-jre as I cannot find org.spark_project.guava used in the table connector.

TableConnector.scala:30:import org.spark_project.guava.util.concurrent.RateLimiter

**Comment by jacobfi** [comment]
Hi yeungp
I have fixed the guava dependency to 14.0.1 (https://search.maven.org/artifact/com.google.guava/guava/14.0.1/bundle). This is the version used by the latest Spark release (2.3.1).
Try and add `"com.google.guava"%"guava"%"14.0.1"` to your project. The fix will be on version 0.3.0 of spark-dynamodb, which should be available on Maven by tomorrow.

I hope this helps,
Jacob

**Comment by cosmincatalin** [comment]
#5

**Comment by 1ambda** [comment]
In case of using gradle for the build tool, you might specify guava version in this way.

```
configurations.all {
    // https://github.com/apache/spark/blob/master/pom.xml#L512
    resolutionStrategy.force "com.google.guava:guava:14.0.1"
}
```
