### ISSUE TITLE
Filter Pushdown

### ISSUE THREAD

**Issue by boyaryn** [audienceproject/spark-dynamodb#50]
I can't get filter pushdown work.
The table `SSEmployeeCountUnion` has about 20 million rows. `CompanyId` is the partition key and `RecordHash` is the sort key. When I run

```
  val unionDataset = spark.read.dynamodbAs[CountRecordEx]("SSEmployeeCountUnion")
  unionDataset.filter($"CompanyId" === 209963).foreach(x => println(x))
```

I expect the result which is 19 records returned immediately but it looks like the full scan is being performed (it runs for a few minutes until I abort the job).

I also tried setting filterPushdown explicitely but it also doesn't work:

```
  val unionDataset = spark.read.option("filterPushdown", "true").dynamodbAs[CountRecordEx]("SSEmployeeCountUnion")
  unionDataset.filter($"CompanyId" === 209963).foreach(x => println(x))
```

Could you help?

**Comment by cosmincatalin** [comment]
@jacobfi , can you please provide some insights into this?
If I remember correctly, we do a scan no matter what. The "predicate pushdown" functionality means that data is not brought into Spark, but is handled by the underlying data store, in this case DynamoDB.

**Comment by jacobfi** [comment]
That is correct.
"Intelligent" filter pushdown is currently not a feature.
The datasource always performs a full scan, however in this case a query would have been much more efficient. I hope to get around to implementing this in the future.

**Comment by boyaryn** [comment]
Thanks for quick reply, guys. Do you mean that currently there is no way to rewrite this piece of code so that a full scan is avoided?

**Comment by jacobfi** [comment]
Unfortunately yes.
If it is a big table I suggest you do a direct query outside of Spark.

**Comment by boyaryn** [comment]
Got it, Jacob. Thanks for the quick reply.

**Comment by jacobfi** [comment]
This issue will have the same solution as #62
