### ISSUE TITLE
Allow giving AWSCredentialsProvider instead of the roleArn string 

### ISSUE THREAD

**Issue by fogrid** [audienceproject/spark-dynamodb#56]
It could be useful if I could also give the role as an AWSCredentialsProvider, instead of the ARN string. 
What I'm working on right now forces me to use AWSCredentialsProvider, and it means I can't make use of this module, since I can't just give the string.

**Comment by fogrid** [comment]
Is there a plan to implement this functionality? 
If there is, how long should this take until it's available?

**Comment by cosmincatalin** [comment]
As it is right now, we don't have a fixed plan for this. We'll post an update here should that change. Also, anyone can pick this, we're more than happy to accept community contributions.

**Comment by fogrid** [comment]
Hey, I added this functionality by adding an option of "providerClassName", which is optionally used to create an object of AWSCredentialsProvider from this class.
Would you like to add this change to this project?

**Comment by fogrid** [comment]
@cosmincatalin kindly reminder

**Comment by cosmincatalin** [comment]
Where's this added, I don't see the PR?

**Comment by fogrid** [comment]
I didn't manage to create one yet, getting permission denied. 
Thought I needed approval creating the PR, but I'm probably doing something wrong. Any idea what?
Sorry for being green :)

**Comment by cosmincatalin** [comment]
Everybody starts somewhere, thank you for taking the time to contribute.
Normally, you should fork the repository into you account and make the modifications there. Then in GitHub you should have the option of creating a Pull Request. GitHub makes that somehow easy. If you have problems doing that, give us a link to your modified code and we'll what can be done to bring it in our main repo.

**Comment by fogrid** [comment]
I see, so the problem was I tried to branch instead of forking. I'll fork it instead
