### ISSUE TITLE
No data retrieved from table

### ISSUE THREAD

**Issue by bmgraff** [audienceproject/spark-dynamodb#6]
I am having some issues getting data from a DynamoDB table. There are no errors, but when I print the schema, the only result is `root`. Doing a show is similar, with 
```
++
||
++
++
```

On a whim, I tried retrieving another of our tables. Everything was perfect, so I tried all 9 of our organization's tables. Two displayed the symptoms detailed above (no rows, no columns) while the rest had no problems. I have tried to compare and contrast the tables, but I see no patterns.

At this point, I'm not certain how to debug this issue. What suggestions do you have?

**Comment by bmgraff** [comment]
Thanks for the response, Jacob.

Unfortunately, I get the same behaviors with that option. Anything else?

**Comment by jacobfi** [comment]
Hi bmgraff
Can you confirm that you are using version 0.3.0 of the library?
Thanks, Jacob

**Comment by jacobfi** [comment]
Hi Benjamin
If you are up for doing some debugging yourself, the first place I would put a breakpoint would be here: https://github.com/audienceproject/spark-dynamodb/blob/master/src/main/scala/com/audienceproject/spark/dynamodb/connector/TableConnector.scala#L75
Check that the scan request to Dynamo looks right.

If it doesn't get in there, perhaps the issue is with the throughput calculator. Check here that item limit is non-zero here:
https://github.com/audienceproject/spark-dynamodb/blob/master/src/main/scala/com/audienceproject/spark/dynamodb/connector/TableConnector.scala#L60

I hope this can help.

**Comment by bmgraff** [comment]
This helps. Thank you.

The item limit is zero. In this case, the `bytesPerRCU` is the default of 4000 and the `readLimit` is 5, because it's a configuration table that doesn't get accessed very often. It autoscales when necessary. However, the `avgItemSize` is > 40,000, yielding a `itemLimit` of 0.

I see a few solutions. First, increase the `bytesPerRCU` option, but this requires me to know something about my table in advance which I may not know. Also, I don't know how this option affects the read/scan behavior.

Second, check for autoscaling. If it doesn't autoscale, then nothing is different and I will get the same result as I do now. If it does, then we can re-set the readLimit in compliance with the `maxCapacity` of the autoscale. This might help. I will submit a pull request, but it's kind of ugly and probably doesn't fit your code very well. Also, there are no tests, since I don't think you can mock the autoscaling stuff, since it's separate from DynamoDb.

Third, maybe something could be done to at least get the schema of the table, regardless of average record size. I mean, that seems wrong somehow that you can't even get a record because your read capacity is too small to read a record. Is that even possible? I don't know DynamoDb that well.
 
There may be other/better options that I don't see, of course. If you need anything else from me, let me know.

**Comment by bmgraff** [comment]
Thanks, Jacob. I look forward to the fix.

**Comment by jacobfi** [comment]
Hi Benjamin
Version 0.3.1 is on Maven Central, however it doesn't do anything about autoscaling, so you may still have to use a workaround for that. Apart from your own fix, you could try setting the `targetCapacity` parameter to an appropriate factor of the base capacity to match the autoscaling cap.
Good luck, Jacob
