### ISSUE TITLE
Please support spark 3.0

### ISSUE THREAD

**Issue by AceHack** [audienceproject/spark-dynamodb#68]
When I try to write to dynamo from a different source other than dynamo on spark 3.0, I get the following error:

DefaultSource does not allow create table as select

**Comment by cosmincatalin** [comment]
Does this work on Spark 2.X.X?

**Comment by AceHack** [comment]
Yes

**Comment by henbh** [comment]
There is an expectation of support in Spark 3?

**Comment by AceHack** [comment]
Yes please support spark 3, this is the last package I need to upgrade.

**Comment by cosmincatalin** [comment]
We'll try to prfioritize this, since there seems to be so much demand.

**Comment by jacobfi** [comment]
Release v1.1.0 is on it's way to Maven Central. I have upgraded to Spark 3, and as a result future releases will be on Scala 2.12 only and incompatible with Spark 2.x.x.
Closing this issue. Please open new ones if there are bugs in the integration to Spark 3.

**Comment by AceHack** [comment]
Spark 2.4.x supports scala 2.12

**Comment by AceHack** [comment]
How long before we should see the new version on maven?

**Comment by AceHack** [comment]
Or do you have a snapshot repo I could point to in the mean time?

**Comment by jacobfi** [comment]
The package is up here now:
https://search.maven.org/search?q=spark-dynamodb

You are right that Spark 2.4.x supports Scala 2.12, but the Data Source API has diverged significantly in Spark 3 from how it looked in Spark 2, so the code is no longer backwards compatible.
