### ISSUE TITLE
Getting started 

### ISSUE THREAD

**Issue by youcefjd** [audienceproject/spark-dynamodb#82]
Hi,

I just imported the JARs and attempted to read from a Dynamo DB, using the provided code snippet: 

dynamoDf = spark.read.option("twitter").format("dynamodb").load() #table name is twitter
dynamoDf.show(100)

I get the following error msg: TypeError: option() missing 1 required positional argument: 'value'.

How do I check if indeed Dynamo is connected to Spark via AudienceProject? Do you have a small example of how to set it up on PySpark?

Thanks for the good work!

**Comment by jacobfi** [comment]
Hi
You are missing an argument to the tablename option. The line should read:
`dynamoDf = spark.read.option("tableName", "twitter").format("dynamodb").load() `
