### ISSUE TITLE
Projection pushdown feature similar to Filter pushdown

### ISSUE THREAD

**Issue by viveksb007** [audienceproject/spark-dynamodb#89]
There can be projection pushdown similar to filter pushdown. This would save data transfer bandwidth from DynamoDB to the spark application.

Not sure if this feature is already there. If not this can be taken as a feature  addition.

Ref - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html

**Comment by jacobfi** [comment]
Hi. This feature is already implemented. Thank you for your interest in the project.
Closing this issue.
